### ISSUE TITLE
Add discountAmount to Place additionalProperties.future

### ISSUE THREAD

**Issue by benediktdertinger** [goodmap/gooddb-backend#24]

**Comment by benediktdertinger** [comment]
How shall we structure this? @simonkoehl 

1. Do we have to distinguish between different shopping branches (e.g. clothes, food) or do we only have an incremental scale that will be applied like priceRange 1 or 2 for all branches?
2. We should centralize this information to be sure it will be updated in all places/client apps. Therefore we need to know all the needs the client apps will have (e.g. The Bonus app needs the max. percentage a merchant offers etc.)

**Comment by simonkoehl** [comment]
Hey!
1) an incremental scale that will be applied like priceRange 1 or 2 for all branches
2) this makes sense. So far regarding the Bonus program, I can think of:
- priceRange
- discount (see 1))
- partner since (dtime stamp)

"partner since" können wir nutzen um bspw. anzuzeigen
- wer neu ist  
- oder wenn das Datum in der Zukunft liegt den Partner auszublenden aber ein vereinbartes Startdatum schon früher in der Datenbank einzutragen.

**Comment by elbotho** [comment]
Wären da nervige, aber evtl. sinnvolle Sonderregeln wie "x€ Startguthaben" oder "Rabatt nur auf Service 1" auch abbildbar?

**Comment by simonkoehl** [comment]
@elbotho Ich denke soetwas wird es zumindest absehbar aus unterschiedlichen Gründen erstmal nicht geben

**Comment by simonkoehl** [comment]
@benediktdertinger btw. all partners offer 5% discount on every purchase

**Comment by benediktdertinger** [comment]
Okay, to sum up:

1. All branches will share the same price ranges
2. Price ranges will structured as incremental scale like: 1,2,3 etc.
3. We also add a timestamp for the date the place became a partner
4. We need another collection to hold the details for each price range holding details about: 
a)   The applied discount amount.  Currently a float like so: `0.05 -> 5%`; Will this always be a percentage value?
b)   The branch?
c)   Any further detail?
8. A place can only have one price range, right?
